In [1]:
import numpy as np

In [48]:
january = np.array([-2,  5, -5,  6, -2,  0,  6,  2,  8,  0,  6, -1,  3,  3,  7,  0, -5,
        7,  4,  7,  8, -1,  5, -2,  3, -3, -2,  7,  8,  4,  2])

In [49]:
mask = january > 0 

In [50]:
january[mask]

array([5, 6, 6, 2, 8, 6, 3, 3, 7, 7, 4, 7, 8, 5, 3, 7, 8, 4, 2])

In [51]:
january

array([-2,  5, -5,  6, -2,  0,  6,  2,  8,  0,  6, -1,  3,  3,  7,  0, -5,
        7,  4,  7,  8, -1,  5, -2,  3, -3, -2,  7,  8,  4,  2])

In [52]:
january[january >= 0 ]

array([5, 6, 0, 6, 2, 8, 0, 6, 3, 3, 7, 0, 7, 4, 7, 8, 5, 3, 7, 8, 4, 2])

In [53]:
# Comparez les températures supérieures et inférieures à 0.

In [54]:
january >= 0 

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True, False,  True, False, False,
        True,  True,  True,  True])

In [55]:
january < 0 

array([ True, False,  True, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False,  True, False,  True,  True,
       False, False, False, False])

In [56]:
# on fait la somme sur un tableau de True et False Numpy compte le nombre de True
np.sum( january >= 0 )

22

In [57]:
np.sum( january < 0  )

9

In [58]:
# 
np.sum( january >= 0 ) > np.sum( january < 0  )

True

In [59]:
january[january >= 0 ].size

22

In [60]:
# Donnez le pourcentage des températures positives sur le mois.
np.round ( ( np.sum( january >= 0 ) / january.size ) * 100, 2 )

70.97

In [61]:
# Créez un tableau days pour les jours du mois et donnez les jours pour lesquels la température était supérieure à 0.
days =  np.arange(1, 32 )

In [62]:
days

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [63]:
# Créez un tableau days pour les jours du mois et donnez les jours pour lesquels la température était supérieure à 0.
days[january >= 0 ]

array([ 2,  4,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 18, 19, 20, 21, 23,
       25, 28, 29, 30, 31])

In [64]:
days[ (january >= 0 ) & (january < 5 )]

array([ 6,  8, 10, 13, 14, 16, 19, 25, 30, 31])

In [65]:
(january >= 0 ) & (january < 5 )

array([False, False, False, False, False,  True, False,  True, False,
        True, False, False,  True,  True, False,  True, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False,  True,  True])

In [66]:
# Donnez toutes les températures supérieures à 0 à partir du dixième jour du mois.

np.array([True, False, True ]) & np.array([True, True, True ])

array([ True, False,  True])

In [67]:
mask = ( days >= 10 ) & ( january > 0 )

days[mask]

array([11, 13, 14, 15, 18, 19, 20, 21, 23, 25, 28, 29, 30, 31])

In [68]:
# Remplacez maintenant les températures négatives par la moyenne des températures positives

average = round( np.sum ( january[january > 0] ) / january.size , 2 )

print(average)

3.26


In [71]:
january = january.astype(float)

january[january < 0 ] = average

print(january)

[3.26 5.   3.26 6.   3.26 0.   6.   2.   8.   0.   6.   3.26 3.   3.
 7.   0.   3.26 7.   4.   7.   8.   3.26 5.   3.26 3.   3.26 3.26 7.
 8.   4.   2.  ]


In [83]:
# permet de créer un jeu de données aléatoires fixe 
np.random.seed(42)
notes = np.random.randint(1, 21, size = 50 )

In [84]:
notes

array([ 7, 20, 15, 11,  8,  7, 19, 11, 11,  4,  8,  3,  2, 12,  6,  2,  1,
       12, 12, 17, 10, 16, 15, 15, 19, 12, 20,  3,  5, 19,  7,  9,  7, 18,
        4, 14, 18,  9,  2, 20, 15,  7, 12,  8, 15,  3, 14, 17,  4, 18])

### Dire combien de notes sont supérieurs à 10
### Supérieur à 10 et pair 
### Dire combien de notes sont supérieur à la moyenne
### Ajoutez .5 aux notes comprises entre 10 et 11 de manière large à l'aide d'un mask

In [85]:
notes[ notes > 10 ]

array([20, 15, 11, 19, 11, 11, 12, 12, 12, 17, 16, 15, 15, 19, 12, 20, 19,
       18, 14, 18, 20, 15, 12, 15, 14, 17, 18])

In [89]:
notes[ (notes > 10 ) & ( notes % 2 == 0 )]

array([20, 12, 12, 12, 16, 12, 20, 18, 14, 18, 20, 12, 14, 18])

In [90]:
# dire combien de notes sont supérieur à la moyenne
average_note = np.mean(notes)

np.sum( notes > average_note )

27

In [93]:
notes = notes.astype(float)

notes[ (notes >= 10) & (notes <= 11 ) ] += .5 

print(notes)

[ 7.  20.  15.  11.5  8.   7.  19.  11.5 11.5  4.   8.   3.   2.  12.
  6.   2.   1.  12.  12.  17.  10.5 16.  15.  15.  19.  12.  20.   3.
  5.  19.   7.   9.   7.  18.   4.  14.  18.   9.   2.  20.  15.   7.
 12.   8.  15.   3.  14.  17.   4.  18. ]
